name: pywisher

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "${{ github.actor }}"
          echo "${{ github.job }}"
          echo "${{ github.run_id }}"

      - name: execute main.py
        env:
          KEY_ID: ${{ secrets.KEY_ID }}
          KEY_SECRET: ${{ secrets.KEY_SECRET }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
        run: python src/main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
