name: pywisher

on:
  schedule:
    - cron: "30 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          sudo timedatectl set-ntp true
          timedatectl

      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute main.py
        env:
          KEY_ID: ${{ secrets.KEY_ID }}
          KEY_SECRET: ${{ secrets.KEY_SECRET }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
        run: python src/main.py

      - name: commit changes
        run: |
          git config --local user.email "aps08@users.noreply.github.com"
          git config --local user.name "aps08"
          git add -A
          git commit -m "Automated Commit"
          git push
